# Generated by Django 5.0.3 on 2024-03-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
